[package]
name = "system_thread_concurency"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["affinity", "channels", "dashing", "deadlocks", "divide_work", "footgun-fixed_with_atomic", "footgun-sharing_data_with_atomics", "functions_to_worker_threads", "hello", "mutexes", "parking_threads", "rayon_iters", "rwlocks", "scoped_threads", "thread_builder", "thread_priorities", "work_queue"]
